### ISSUE TITLE
Implement /badges page

### ISSUE THREAD

**Issue by sergeyklay** [phanbook/phanbook#105]

**Comment by Ultimater** [comment]
Can you assign this to me?

**Comment by mvenkat507** [comment]
Hi,

Can we know the update on this badges and rewards code?

**Comment by duythien** [comment]
@Ultimater Any update :)

**Comment by Ultimater** [comment]
Currently working on stability and architectural design changes.
I won't be able to tackle this feature request for another two or three months.
