### ISSUE TITLE
Add right sidebar for the pages

### ISSUE THREAD

**Issue by sergeyklay** [phanbook/phanbook#157]
For example `/tags/16/volt`

**Comment by Ultimater** [comment]
Are you referring to the breadcrumbs?  
  
![breadcrumbs-phalcon](https://user-images.githubusercontent.com/1922199/29441381-cc1a37aa-837f-11e7-9fe2-ce6bf4934e62.png)  

And you want it to say something like `Home / Tags / PhalconPHP` in my case rather than PostByTag?  
Working on it.
