### ISSUE TITLE
Cannot install phanbook on WAMP

### ISSUE THREAD

**Issue by binarynos** [phanbook/phanbook#166]
Hello,
I am trying to install phanbook on WAMP but i get the error page titled "Site maintenance". I checked the log and found:
```
[Thu, 10 Nov 16 14:54:36 +0000][ERROR] Syntax error, unexpected token EQUALS, near to ' :objectId: AND object = :object:', when parsing: SELECT COALESCE(SUM(positive),0) AS positive, COALESCE(SUM(negative),0) AS negative FROM Phanbook\Models\VoteWHERE objectId = :objectId: AND object = :object: (158)
[Thu, 10 Nov 16 14:54:36 +0000][ERROR] #0 [internal function]: Phalcon\Mvc\Model\Query->parse()

#1 [internal function]: Phalcon\Mvc\Model\Query->execute()
#2 \vhosts\phanbook\core\common\models\ModelBase.php(92): Phalcon\Mvc\Model\Manager->executeQuery('SELECT COALESCE...', Array)
#3 \vhosts\phanbook\content\cache\volt\vhosts_phanbook_content_themes_default_partials_question.volt.php(3): Phanbook\Models\ModelBase->getVotes('66', 'posts')
#4 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('C:\\Users\\czone\\...', Array, false)
#5 [internal function]: Phalcon\Mvc\View->_engineRender(Array, 'partials/questi...', false, false)
#6 [internal function]: Phalcon\Mvc\View->partial('partials/questi...', Array)
#7 \vhosts\phanbook\content\cache\volt\vhosts_phanbook_content_themes_default_partials_list-posts.volt.php(2): Phalcon\Mvc\View\Engine->partial('partials/questi...', Array)
#8 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('C:\\Users\\czone\\...', Array, false)
#9[internal function]: Phalcon\Mvc\View->_engineRender(Array, 'partials/list-p...', false, false)
#10 [internal function]: Phalcon\Mvc\View->partial('partials/list-p...', NULL)
#11 \vhosts\phanbook\content\cache\volt\vhosts_phanbook_content_themes_default_post.volt.php(55): Phalcon\Mvc\View\Engine->partial('partials/list-p...')
#12 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('C:\\Users\\czone\\...', Array, true)
#13 [internal function]: Phalcon\Mvc\View->_engineRender(Array, 'post', true, true, NULL)
#14 [internal function]: Phalcon\Mvc\View->render('posts', 'index', Array)
#15 \vhosts\phanbook\index.php(56): Phalcon\Mvc\Application->handle()
#16 {main}
```

What might have gone wrong?
Thanks

**Comment by sergeyklay** [comment]
@binarynos Could you please provide MySQL vesion and used phanbook branch ?

**Comment by binarynos** [comment]
Hello @sergeyklay MySQL version is 5.6.33

**Comment by sergeyklay** [comment]
@binarynos Did you use `master` or `develop` branch?

**Comment by binarynos** [comment]
I used the `master` branch

**Comment by sergeyklay** [comment]
So could you try the `develop` branch

**Comment by binarynos** [comment]
@sergeyklay okay I will try and post the results here

**Comment by binarynos** [comment]
So I tried the `develop` branch but now it shows another error `Fatal error: Class 'Memcached' not found in \vhosts\phanbook\core\common\Application.php on line 172`

**Comment by sergeyklay** [comment]
You have to install Memcached extension. I'll improve this. To use another cache backend in case of absence of Memcached

**Comment by binarynos** [comment]
I am using PHP 5.6 but could not find a Windows Memcached version for PHP 5.6. I tried to use the Memcached 1.2.6 found [here](http://code.jellycan.com/files/memcached-1.2.6-win32-bin.zip) and PHP Memcached extension found [here](http://windows.php.net/downloads/pecl/releases/memcache/3.0.8/php_memcache-3.0.8-5.6-ts-vc11-x86.zip). But I still get the same error. I am not a programmer so I think I do not have the technical knowledge to do that, so I think that I should just wait for the stable release of Phanbook with easier installation process.
Thanks

**Comment by duythien** [comment]
@binarynos in mean time you can test it with vagrant

**Comment by sergeyklay** [comment]
@binarynos  Let me fix memcached issue. I'll do it today

**Comment by binarynos** [comment]
Any updates on this issue, is it impossible to install phanbook without Memcached?

**Comment by sergeyklay** [comment]
@binarynos Could you please try `develop` branch?

**Comment by sergeyklay** [comment]
@binarynos For setting up the cache driver please refer to the https://github.com/phanbook/phanbook/pull/178

**Comment by binarynos** [comment]
@sergeyklay  I tested again with the latest `develop` branch using Redis as cache driver but this time I see a completely different issue. I get error:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045]
Access denied for user ''@'localhost' (using password: NO)'
in \vhosts\phanbook\core\common\library\Providers\DatabaseServiceProvider.php:55
```

I have double checked the database configuration : `username`, `host`, database name, and database charset in core/config/config.php and everything is correct.

Any suggestions?

**Comment by sergeyklay** [comment]
@binarynos could you please provide your local `.env` file? I'm interested in **`DB_`** part.
For example my `.env` file:

```
DB_DSN='mysql:host=localhost;dbname=phanbook'
DB_USERNAME=root
DB_PASSWORD=
DB_DATABASE=phanbook
DB_CHARSET=utf8
DB_HOST=localhost
DB_CONNECTION=mysql
```

**Comment by binarynos** [comment]
@sergeyklay here is the .env file

``` APPLICATION_ENV=local

APP_REPO=https://github.com/phanbook
APP_SALT=put-some-secret-salt-here
APP_DEBUG=true
APP_URL=http://phanbook.dev
APP_BASE_URI=/
APP_STATIC_URL=/
APP_TIMEZONE=UTC

DB_DSN='mysql:host=localhost;dbname=phanbook'
DB_USERNAME=root
DB_PASSWORD=
DB_DATABASE=phanbook
DB_CHARSET=utf8
DB_HOST=localhost
DB_CONNECTION=mysql

LANG_CODE=en
LANG_USE_GETTEXT=false

ANALYTIC_ID=
ANALYTIC_CLIENT_ID=
ANALYTIC_SECRET=
ANALYTIC_REDIRECT_URI=http://phanbook.dev/oauth/google/access_token

GITHUB_CLIENT_ID=
GITHUB_SECRET=
GITHUB_REDIRECT_URI=http://phanbook.dev/oauth/github/access_token

FACEBOOK_CLIENT_ID=
FACEBOOK_SECRET=
FACEBOOK_REDIRECT_URI=http://phanbook.dev/oauth/facebook/access_token

BEANSTALK_ENABLED=false
BEANSTALK_HOST=localhost
BEANSTALK_PORT=11300

ELASTIC_INDEX=phanbook
ELASTIC_TYPE=posts

MAIL_DRIVER=smpt
MAIL_FROM_NAME=Phanbook
MAIL_FROM_ADDRESS=no-reply@phanbook.dev
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

COOKIE_LIFETIME=691200

SECURITY_HASHING_FACTOR=12

SESSION_DRIVER=Files
SESSION_LIFETIME=600
SESSION_UNIQUE_ID=phanbook_

VIEW_CACHE_DRIVER=File
VIEW_CACHE_LIFETIME=86400
VIEW_CACHE_PREFIX=phanbook_
VIEW_CACHE_FORCE=false

DATA_CACHE_FRONTEND=Data
DATA_CACHE_DRIVER=File
DATA_CACHE_LIFETIME=86400
DATA_CACHE_PREFIX=phanbook_
DATA_CACHE_FORCE=false

CACHE_DRIVER=file
CACHE_PREFIX=phanbook_
CACHE_LIFETIME=86400

MEMCACHED_HOST=127.0.0.1
MEMCACHED_PORT=11211
MEMCACHED_WEIGHT=100

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_INDEX=0

METADATA_DRIVER=Memory

LOGGER_FORMAT='[%date%][%type%] %message%'
LOGGER_LEVEL=debug
```

Actually I only modified the DB part, other configuration is the same as the .env.example file. Do I need to change something elsewhere, like I am confused in the CACHE part?

**Comment by sergeyklay** [comment]
@binarynos 
Hm, looks like this is Windows-related issue. See: https://github.com/vlucas/phpdotenv/issues/109
As workaround you can put db credentials directly to the `core/config/config.php`

**Comment by binarynos** [comment]
> As workaround you can put db credentials directly to the core/config/config.php

As I already [said](https://github.com/phanbook/phanbook/issues/166#issuecomment-260188058) db credentials are already present in `core/config/config.php`. But for some reason it can't connect to database. There is some other error information. I can post it here if you need.
Thanks

**Comment by binarynos** [comment]
Sorry, I accidently closed the issue

**Comment by sergeyklay** [comment]
> in \vhosts\phanbook\core\common\library\Providers\DatabaseServiceProvider.php:55

Well, at least you can dump config here to see what exactly now there

**Comment by duythien** [comment]
@binarynos To test correct you should be set password for mysql because some time https://github.com/phanbook/phanbook/blob/develop/core/config/config.php#L22

```
'password' =>"",
```

It will not be understand is empty

**Comment by binarynos** [comment]
@sergeyklay sorry i don't understand, i think you are asking for the `config.php` file. The only changes i made to the file are:

```
 /**
     * The database credentials
     */
    'database' => [
        'mysql' => [
            'host'     => env('localhost'),
            'username' => env('root'),
            'password' => env('********'),
            'dbname'   => env('phanbook'),
            'charset'  => env('utf8'),
        ]
    ],
```

Rest of the code is the same
@duythien the password is already set

**Comment by sergeyklay** [comment]
@binarynos You have to use:

``` php
    'database' => [
        'mysql' => [
            'host'     => 'localhost',
            'username' => 'root',
            'password' => '********',
            'dbname'   => 'phanbook',
            'charset'  => 'utf8',
        ]
    ],
```

See how `env( )` works: https://github.com/phanbook/phanbook/blob/develop/bootstrap/helpers.php#L139-L159

**Comment by binarynos** [comment]
@sergeyklay  Okay, I got it working. So, this was the problem. Sorry again to bother you and thanks a lot!

**Comment by sergeyklay** [comment]
@binarynos How about first question? Is issue solved?

**Comment by sergeyklay** [comment]
@binarynos

**Comment by binarynos** [comment]
@sergeyklay, which issue? The cache driver issue? Yes, it's fixed. I configured .env file to use Redis and everything is working as expected

**Comment by sergeyklay** [comment]
@binarynos I meant your first message in this issue

**Comment by binarynos** [comment]
@sergeyklay yes that problem too is fixed now

**Comment by sergeyklay** [comment]
Thanks
