### ISSUE TITLE
Some pages on your website are down

### ISSUE THREAD

**Issue by arnoldbird** [phanbook/phanbook#210]
All the subdomains are down...
blog.phanbook.com
themes.phanbook.com
etc

Also, the "Follow Along" social buttons on your site are broken at the moment, if you're not aware.

Thanks.  Look forward to reading more about phanbook.

**Comment by duythien** [comment]
Hello

I have just fix some domain down, and I also hide the button social you can see here https://github.com/phanbook/portal.phanbook/commit/e291718ad0b44d0795e274e7b51e82aa0d8de961

**Comment by arnoldbird** [comment]
It's not fixed at the moment.  The pages won't load.  I tried on safari and Firefox.  Thank you.

**Comment by duythien** [comment]
You have tries clean history ? you can see test https://proxy-nl.hide.me/go.php?u=hdds1QFeH2VnPI9uhsO6%2FVIMCA0l&b=5&f=norefer

**Comment by arnoldbird** [comment]
I can see the pages through "hide me", yes.  But somehow I still can't see any of the sub domains in any of my browsers or devices without using "hide me".

**Comment by arnoldbird** [comment]
Now I can see the sub domains in my browser without using "hide me".  I'll close this issue.  Thanks!
