### ISSUE TITLE
The name "phanbook"

### ISSUE THREAD

**Issue by arnoldbird** [phanbook/phanbook#211]
re: "the name Phanbook is mean - Phan(Phalcon PHP)book(the your note book)".

I don't think it works.  People will come to this software primarily for the Q&A functionality.  I don't know what the name should be, but "Phanbook" sounds too much like facebook.  Even something like "Phalcon Q&A" would be better.

Thanks!  I look forward to trying the software very soon.

**Comment by sergeyklay** [comment]
Cc: @duythien

**Comment by duythien** [comment]
@arnoldbird Yep Maybe you right but for now I'm fine with the name phanbook, if we change name it will be more to refactor code and SEO on google

**Comment by arnoldbird** [comment]
The name will hold you back.  I'm a native English speaker, and at least in English, the sound & sense of "phanbook" is very bad.  It will limit developer interest and adoption by organizations.  It will also hold phalcon back, since phanbook appears to be the "killer app" that can popularize phalcon.  

It sends a bad message when the framework's most important app has a name that's at cross purposes with the project.  The name does not make logical sense for the project.  It makes the project seem temporary.  It makes it seem like you have a big gap in the team's skill set.  I've seen this mistake made by other projects. They say, we'll change the name later.  Later on, the project doesn't exist.  It won't get easier to change the name later.

**Comment by arnoldbird** [comment]
Other name options:

- **cast** -- This is the word for a flock of falcons.  Flock ~ organized community.  Also the word for a group of actors working on a movie.  Also: "cast a spell." "Cast of characters."  Also rhymes with fast.  
- **phlock**
- **phalcon Q&A**.
- **phanswers**
- **phlux** -- Might collide with https://github.com/rphcrosby/phlux/commits/master
- **elephant** -- Just because.  "Elephants never forget."  Elephants are very social, communal animals.  I think this would be ok, despite it being used as the php mascot: https://wwphp-fb.github.io/faq/community/elephpant/
- **babar** -- Famous and heroic elephant: https://en.m.wikipedia.org/wiki/Babar_the_Elephant -- Note that Babar has a monkey friend named Zephir!
- **flit** -- http://www.dictionary.com/browse/flit
- **fence** -- https://en.m.wikipedia.org/wiki/Fence
- **tembo** -- Swahili for elephant. https://www.howtopronounce.com/swahili/tembo/
- **phlight** -- http://www.dictionary.com/browse/flight -- "flight of fancy." "Flight of stairs."

**Comment by duythien** [comment]
@arnoldbird Ok I will take look and thinking again :)

**Comment by duythien** [comment]
@sergeyklay Any idea welcome :)

**Comment by arnoldbird** [comment]
I'll add more to my list above as I think of them.

**Comment by sergeyklay** [comment]
First of all I'm not sure that the name should be composed of Phalcon or PHP.

**Comment by arnoldbird** [comment]
Sergeyklay,

I'm not sure about that either. 

Right this moment, I like "tembo" best.  It's short, simple, neutral, no namespace collision, and no licensing problem. And it's non-English so it reinforces that this is an international project.

I like "babar" but maybe there could be a licensing problem.  Also, it's not entirely neutral because some people think the Babar stories support colonialism.

"Cast" is maybe ok but could be hard to google because "cast" is used in programming to mean casting a variable as a certain type.  No such confusion with tembo.

Tembo is also just an easy word to say.

**Comment by sergeyklay** [comment]
I like Tembo

**Comment by sergeyklay** [comment]
* [Tembo](https://www.houdah.com/tembo/?lang=en) - Friendly File Search Assistant
* [tembo.in](http://www.tembo.in/) - India's leading manufacturer of A4 copier papers-xerox papers, galavanised hose clamps, ball pens, pencils, noteboks, long note books and other products
* [Project TEMBO](http://projectembo.org/) - stands for Tanzania Education and Micro-Business Opportunity
* [Tembo Financial](https://www.tembofinancial.com/) - Tembo Financial Inc., licensed by the Financial Services Commission of Ontario

**Comment by arnoldbird** [comment]
The first one (the file search tool) seems like the worst collision.  I don't think the others are a problem.  And I'm not really sure the file search tool is a problem.  I don't know who really needs a tool like that.  People don't even keep files on their computers anymore.  I think it might be ok to collide with that, but I'm not sure.  More an one thing can be called "elephant" so maybe more than one thing can be called "tembo"?
