### ISSUE TITLE
Questions do not save

### ISSUE THREAD

**Issue by arnoldbird** [phanbook/phanbook#213]
When I try to save a question on the **frontend**, it doesn't save.  This page loads:  posts/save
  
In the error log I see...

[Sun Dec 25 11:16:41.010392 2016] [:error] [pid 4381] [client 127.0.0.1:51962] PHP Warning:  Invalid argument supplied for foreach() in /var/www/yo/phanbook/content/cache/volt/_var_www_tembo_phanbook_content_themes_default_partials_right-side.volt.php on line 76, referer: http://yo.mysite.com/posts/save

In the backend, I can save posts.

**Comment by duythien** [comment]
Hello @arnoldbird 

I have just fix it in to branch develop so you can pull last code to test again

**Comment by arnoldbird** [comment]
I think your change may have introduced a new bug.  I can no longer access backend/dashboard or backend/themes/custom

Because I can't access the backend anymore, I can't create tags, and tag is a required field in the question form.

**Comment by duythien** [comment]
Nope. This is not my bug because when you rollback your data at that issue https://github.com/phanbook/phanbook/issues/215, you need go to mysql console to update field admin in table users to 'Y'

Then logout and login again, currently your account not admin so you can not access backend

**Comment by arnoldbird** [comment]
Yep, that was it.  And now I can save questions on the frontend as well.
