### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by brainfoolong** [phanbook/phanbook#218]
I've installed phanbook via this instructions
http://phanbook.com/docs/manual

Now i'm getting always this error when i try to access the mainpage. I can't get it working.
Composer installation was successfull without errors. `composer version 1.3.1`

	composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader
	Loading composer repositories with package information
	Installing dependencies from lock file
	Package operations: 15 installs, 0 updates, 0 removals
	  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
	  - Installing danielstjules/stringy (2.3.2) Loading from cache
	  - Installing psr/log (1.0.2) Loading from cache
	  - Installing pimple/pimple (v3.0.2) Loading from cache
	  - Installing monolog/monolog (1.21.0) Loading from cache
	  - Installing symfony/event-dispatcher (v2.8.13) Loading from cache
	  - Installing guzzle/guzzle (v3.9.3) Loading from cache
	  - Installing elasticsearch/elasticsearch (v1.4.1) Loading from cache
	  - Installing erusev/parsedown (1.6.1) Loading from cache
	  - Installing google/apiclient (v1.1.8) Loading from cache
	  - Installing league/flysystem (1.0.32) Loading from cache
	  - Installing league/fractal (0.9.1) Loading from cache
	  - Installing league/oauth2-client (0.10.1) Loading from cache
	  - Installing swiftmailer/swiftmailer (v5.4.3) Loading from cache
	  - Installing vlucas/phpdotenv (v2.4.0) Loading from cache
	Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
	Generating optimized autoload files

PHP 7.1 on ubuntu.

	PHP message: PHP Fatal error:  Uncaught Error: Class 'Phalcon\Loader' not found in /srv/www/f/bootstrap/autoloader.php:20
	Stack trace:
	#0 /srv/www/f/public/index.php(17): require()
	#1 {main}
	  thrown in /srv/www/f/bootstrap/autoloader.php on line 20

**Comment by sergeyklay** [comment]
Try without `--no-scripts`

**Comment by brainfoolong** [comment]
Thx for fast answer. Didn't helped. I've also removed all contents in `vendor` and than ran the composer again. Not worked.

**Comment by sergeyklay** [comment]
```
$ cd /tmp
$ composer create-project phanbook/phanbook --ignore-platform-deps 
```

**Comment by brainfoolong** [comment]
Sorry

	[Symfony\Component\Console\Exception\RuntimeException]
	The "--ignore-platform-deps" option does not exist.

**Comment by brainfoolong** [comment]
Btw. Composer version: `You are already using composer version 1.3.1 (stable channel).`

**Comment by brainfoolong** [comment]
The thing is, i understand why this cannot work.

1. `index.php` directly include `bootstrap/autoloader.php`
2. `bootstrap/autoloader.php` first line of code call `(new Loader)`

It's impossible that this could work because there is no code that can load the `Phalcon/Loader`, isn't it?

**Comment by sergeyklay** [comment]
Do you have `phalcon.so` extension loaded?

**Comment by sergeyklay** [comment]
`--ignore-platform-deps` => `--ignore-platform-reqs`

**Comment by brainfoolong** [comment]
Sorry for bothering, i've not seen the phalcon extension requirement. Unfortunetely, phanbook is than nothing for me.

Thanks for your help.

**Comment by sergeyklay** [comment]
> https://github.com/phanbook/phanbook/blob/master/README.md

> Phanbook is built with Phalcon PHP so it's quick and easy to deploy.
