### ISSUE TITLE
change the license  ?

### ISSUE THREAD

**Issue by kideny** [phanbook/phanbook#234]
i saw phanbook's license is GPLv2，the license can be changed to MIT or BSD license ? 

@duythien

**Comment by duythien** [comment]
Why? I see a open source WordPress have use GPLv2 https://github.com/WordPress/WordPress/blob/master/license.txt#L40 

So that the Phanbook will be great with the license

**Comment by kideny** [comment]
GPLv2 can't be used for company....

**Comment by duythien** [comment]
@sergeyklay Any suggestion?

**Comment by sergeyklay** [comment]
I agree with @kideny . It is reasonable to charge license (MIT or BSD)

**Comment by duythien** [comment]
@kideny Alright, could you add BSD license for Phanbook?

**Comment by kideny** [comment]
no problem!
