### ISSUE TITLE
oauth: passwd is required

### ISSUE THREAD

**Issue by Ultimater** [phanbook/phanbook#240]
![passwd-is-required](https://user-images.githubusercontent.com/1922199/29396933-e81ab8e0-82cf-11e7-979b-64232922dc3e.png)

Steps to reproduce:  
http://phanbook.dev/users/signin -> Click **Sign in using Github**  
Authorize, and when you get forwarded back, then you see the above error.

Cause:  
This is caused by the MySQL table definition for `users` not allowing `NULL` for the "passwd" column.  
Thus user creation via github fails due to the way the model is being used. This I believe also affects the other oauth methods as well.

Fix:  
I believe the best fix is to modify the column and allow it to be `NULL` like so:

    ALTER TABLE `users` CHANGE `passwd` `passwd` VARCHAR(60) CHARACTER SET utf8
    COLLATE utf8_general_ci NULL;

**Comment by duythien** [comment]
Thanks
