### ISSUE TITLE
/backend/users produces a 500 error

### ISSUE THREAD

**Issue by Ultimater** [phanbook/phanbook#243]
Steps to reproduce:  
Login as the admin user: admin:phanbook  
Click the "settings" link on the to of the page.  
Click the DashBoard link.  
Once you're in the Dashboard **double click** "Users".  
You should now be looking at the `/backend/dashboard` page.  
It produces a 500 error and writes a log to `content/logs`:  
```  
[Thu, 17 Aug 17 14:52:57 +0000][ERROR] backend [0]: Column 'admin' doesn't belong to the model or alias 'a', when executing: SELECT a.id, CONCAT(a.firstname, ' ', a.lastname) as name, a.username, a.gender, a.email, a.status, a.admin, a.moderator, a.karma FROM [Phanbook\Models\Users] AS [a] GROUP BY a.id
```
You can run the above directly on the database:

>SELECT a.id, CONCAT(a.firstname, ' ', a.lastname) as name, a.username, a.gender, a.email, a.status, a.admin, a.moderator, a.karma FROM users AS a GROUP BY a.id

Trying that yields `#1054 - Unknown column 'a.admin' in 'field list'`. Removing it from the query and trying again yields `#1054 - Unknown column 'a.moderator' in 'field list'`. After removing that as well, the query executes fine.

Thus, this issue is caused by the `` `users` `` table having no `admin` or `moderator` column. I'm not sure exactly when the schema changed, but I clicked to a year back in the commits and found previous schemas were using: https://github.com/phanbook/phanbook/blob/f0b8b1cf4b554f9d1553d869e22505c2d1946abc/schema/phanbook.sql#L596-L597
Thus it would appear the columns were supposed to represent boolean data consisting of `N`/`Y`.
To determine if a user is an admin, it would seem now that you need to consult three tables:  
`users`, `roles_users`, and `roles`. I see we're currently using:

![roles-table](https://user-images.githubusercontent.com/1922199/29418778-270d6f32-8322-11e7-9230-335b0aed6ed5.png)
Judging by that table, the only column that looks reliable to me would be `type`. If it's set to admin or moderator, then it would seem to me they are a user of that role. Thus it seems we now have a replacement for the missing admin and moderator columns.

I wrote up a join query that looks like this:  
```
SELECT a.id, CONCAT(a.firstname, ' ', a.lastname) as name, a.username, a.gender, a.email, a.status, IF(SUM(c.type = 'admin'),'Y','N') AS admin, IF(SUM(c.type = 'moderator'),'Y','N') AS moderator, a.karma  FROM `users` a LEFT JOIN `roles_users` b ON a.id=b.users_id LEFT JOIN `roles` c ON c.id=b.roles_id GROUP BY a.id
```
Thus it would seem a fix would be to add some joins to our query. Since we're grouping by `a.id`, there won't be an issue of duplicates. Then we can make use of SUM or COUNT. I'm pretty sure SUM makes more sense in this context.

PR is coming shortly.

**Comment by duythien** [comment]
👍

**Comment by sergeyklay** [comment]
Fixed in the `develop` branch. Thank you for contributing!
