### ISSUE TITLE
/backend/store produces 404

### ISSUE THREAD

**Issue by Ultimater** [phanbook/phanbook#245]
Navigate to `/backend/dashboard` and you'll notice a link to "store" in the navigation:  

![dashboard-link](https://user-images.githubusercontent.com/1922199/29422618-a2a694ce-832d-11e7-8266-e73666f9ac4e.png)

Upon clicking it, you get a 404 page:

![backend-store-404](https://user-images.githubusercontent.com/1922199/29422645-b87b9d08-832d-11e7-8153-23765d9fcc0f.png)

Judging by the navigation link, it seems like there's supposed to be a StoreController:

https://github.com/phanbook/phanbook/blob/51cc4d7ff6671f66d7b49dfb94b2e8ec2cc6f6b4/core/modules/backend/views/partials/left-side.volt#L51-L55

There's no such controller in the repo, and I can't find one in the history either.  
Any input?

**Comment by sergeyklay** [comment]
Hmm 🤔 I forgot. Maybe it is semi-finished feature planned for future?

/cc @duythien

**Comment by duythien** [comment]
It's link for feature :) so now we can close this issue
