### ISSUE TITLE
backend/media images not displaying

### ISSUE THREAD

**Issue by Ultimater** [phanbook/phanbook#248]
![backend-media-not-displaying](https://user-images.githubusercontent.com/1922199/29442791-b2969bb2-8388-11e7-9610-e840af16f9f3.png)

My fix is:  `RewriteRule ^(content/uploads)($|/) - [NC,L]`

![backend-media-not-display-after](https://user-images.githubusercontent.com/1922199/29442802-cca60a60-8388-11e7-8fc4-470f4bf54318.png)

**Comment by Ultimater** [comment]
Fixed in the develop branch.

**Comment by sergeyklay** [comment]
@Ultimater Could you add labels to the new issues. This will help us to understand what happens (or happened)

**Comment by sergeyklay** [comment]
Feel free to create new ones if it is necessary
