### ISSUE TITLE
config/options/options.php because No such file or directory

### ISSUE THREAD

**Issue by godeye** [phanbook/phanbook#254]
[Sat Dec 16 07:00:29 2017] [error] [client 171.113.82.181] PHP Warning:  touch(): Unable to create file /srv/www/com/core/config/options/options.php because No such file or directory in /srv/www/com/core/common/tools/ZFunction.php on line 88, referer: http://www.com.com/backend/settings/general
[Sat Dec 16 07:00:29 2017] [error] [client 171.113.82.181] PHP Fatal error:  Uncaught exception 'Exception' with message '<p>You need to set permission for it, just add chmod\n                or chown in directory config, Also you can create file /srv/www/com/core/config/options/options.php for that</p><code> chown -R nginx:nginx -R common/config</code>or#<code> chown -R apache:apache -R common/config</code>' in /srv/www/com/core/common/tools/ZFunction.php:94\nStack trace:\n#0 /srv/www/com/core/common/library/Utils/Phanbook.php(109): Phanbook\\Tools\\ZFunction::makeFile('/srv/www/c...')\n#1 /srv/www/com/core/modules/backend/controllers/SettingsController.php(193): Phanbook\\Utils\\Phanbook->saveConfig(Array)\n#2 [internal function]: Phanbook\\Backend\\Controllers\\SettingsController->saveGeneralAction()\n#3 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(Phanbook\\Backend\\Controllers\\SettingsController), 'saveGeneralActi...', Array)\n#4 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#5 [internal function]: Phalcon\\Dispatcher->dispatch()\n#6 /srv/www/bug in /srv/www/com/core/common/tools/ZFunction.php on line 94, referer: http://www.com.com/backend/settings/general

**Comment by duythien** [comment]
@godeye Just fixed it. To be sure created a file success you need add permission for the folder content/options
