### ISSUE TITLE
Created new logo Phanbook [$50 awarded]

### ISSUE THREAD

**Issue by duythien** [phanbook/phanbook#37]
Hi there,

Currently,  we have a logo but this not good, so we need to re-design a awesome logo, any idea are welcome
##

**Comment by catrobson** [comment]
Some variations of a logo idea - only in black and white at this point to see if you like the general concept before applying any color suggestions.  
![phanbook_logoconcepts](https://cloud.githubusercontent.com/assets/3739227/11261314/38660546-8e41-11e5-8597-654ac331c268.png)

**Comment by glmanhtu** [comment]
I think this logo need an special icon rather than only word. Something similar Phalcon framework logo. It wil make easy for people to realize phanbook with another trademarks

**Comment by duythien** [comment]
@yehnkay  you are right :+1:

**Comment by elioqoshi** [comment]
## Commented also here: https://github.com/opensourcedesign/jobs/pull/70#issuecomment-158381623

@duythien first proposal here. I used a Mockingbird for the logo. The idea behind was that mockingbirds are also called colibri, and "libri" comes from "libre" as in free :)

Let me know what you think
![draft-01](https://cloud.githubusercontent.com/assets/5436686/11299755/ad422022-8f89-11e5-9edf-006ddf6f318f.jpg)

**Comment by elioqoshi** [comment]
Here is another one without stroke
![2-01](https://cloud.githubusercontent.com/assets/5436686/11299786/df75b3f6-8f89-11e5-812f-83e7af67fd89.jpg)

**Comment by duythien** [comment]
@elioqoshi It doesn't look really beautiful, just my opinion

**Comment by elioqoshi** [comment]
@duythien  uhm okay, but can you specify why? I can't improve if I don't get feedback.

**Comment by duythien** [comment]
I'm not sure, first we don't need the text phanbook in logo you can see some logo such as Drupal or Opensouce do not have text

**Comment by elioqoshi** [comment]
erm afaik the only brand without a wordmark is Twitter. 
and of course Drupal has a wordmark:
https://www.google.com/search?q=drupal+logo&biw=1920&bih=945&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjcnLrGlZ_JAhWFBBoKHaUMCV0Q_AUIBigB

I think I'm going to leave this, the instructions are too confusing. 

Good luck!

**Comment by duythien** [comment]
@elioqoshi Ok no problem, I don't have  any idea for logo right now, just want to awesome

**Comment by sergeyklay** [comment]
Hummingbook?

![archilochus-alexandri-002-edit](https://cloud.githubusercontent.com/assets/1256298/11314227/6586c23e-8fec-11e5-8556-520e41e2d830.jpg)

**Comment by sergeyklay** [comment]
[Phalcon](http://www.istockphoto.com/photos/peregrine+falcon?facets={%22text%22:[%22peregrine%20falcon%22],%22pageNumber%22:1,%22perPage%22:100,%22abstractType%22:[%22photos%22],%22order%22:%22bestMatch%22,%22f%22:true})

**Comment by sergeyklay** [comment]
:-1:

**Comment by duythien** [comment]
:)
