### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by elvisfloress** [phanbook/phanbook#40]
Hi, i have a problem with navigation, the section "users, badges, tags" not load.

My server is:
Apache 2.0
PHP Version 5.6.8
Phalcon 2.0.7

What could be the problem?

![captura](https://cloud.githubusercontent.com/assets/15949626/11313502/4990f05e-8fab-11e5-9ffb-0cb1ba077e85.png)

**Comment by duythien** [comment]
@elvidi Currently, We have not add htaccess apache, so it will not working, It work fine with Nginx you can use my vagrant to develop or Docker for production

We will add htaccess later

**Comment by elvisfloress** [comment]
Ok, thank you :)

**Comment by duythien** [comment]
Now it working for font-end :)
