### ISSUE TITLE
Crashed under  PHP Version 7.0.4-1, Phalcon 2.1.0b

### ISSUE THREAD

**Issue by phpclub** [phanbook/phanbook#48]
[10-Mar-2016 10:41:02] WARNING: [pool www] child 4861 exited on signal 11 (SIGSEGV - core dumped) after 29.222294 seconds from start

Web framework delivered as a C-extension for PHP
phalcon enabled
Author  Phalcon Team and contributors
Version 2.1.0b
Build Date  Mar 10 2016 09:56:57
Powered by Zephir   Version 0.9.2a-dev

**Comment by duythien** [comment]
Hi

What is version php? Currently Phalcon PHP have not support PHP 7, so to use Phanbook just updown version php5.6.x
