### ISSUE TITLE
Introduce path helpers

### ISSUE THREAD

**Issue by sergeyklay** [phanbook/phanbook#75]
To avoid using paths like `ROOT_DIR . '/content/options/options.php'` or `ROOT_DIR . 'content/options/options.php'` and possible errors by using (or not using) leading slash we need to introduce path helpers. Something like:
- [x] `app_path()`
- [x] `config_path()`
- [x] `content_path()`
- [x] `themes_path()`
- [x] `modules_path()`
- [x] `logs_path()`

Refs: https://github.com/phanbook/phanbook/pull/74
##

**Comment by duythien** [comment]
👍

**Comment by sergeyklay** [comment]
Added to the `develop` branch
