### ISSUE TITLE
Add function translation for constants

### ISSUE THREAD

**Issue by duythien** [phanbook/phanbook#99]
For example this file https://github.com/phanbook/phanbook/blob/develop/bootstrap/constants.php

If I have add a new constants such as like this 

```
/**
 * For global success message
 * @return String message
*/
define("SUCCESS_MESSAGE", t("Success"));

/**
 * For global error message
*/
define("CSRF_ERROR", t("CSRF validation failed"));

/**
 *  For media feature
*/
define("MEDIA_TITLE", t("Media Library"));

define("MEDIA_UPLOAD", t("Upload"));

define("MEDIA_NOT_FOUND", t("You don't have any media's files here. Please upload first!"));

```

Will be get a error  below

( ! ) Error: Call to undefined function t() in bootstrap/constants.php on line 63
##

**Comment by duythien** [comment]
I see your reasons remove it  https://github.com/phanbook/phanbook/pull/89

**Comment by sergeyklay** [comment]
@duythien This is not a good idea to add translations via global PHP constants (eg `define(...)`). We should avoid this. Use `t(...)` directly in code
